export type Confederation =
  | "UEFA"
  | "CONMEBOL"
  | "CAF"
  | "AFC"
  | "CONCACAF"
  | "OFC";

export interface Team {
  slug: string;
  name: string;
  shortName: string;
  confederation: Confederation;
  fifaCode: string;
  keyword: string;
  volume: number;
  flagCode: string;
  publishDate: string; // ISO date — team page goes live on this date
}

// Helper: is this team published yet?
export function isPublished(team: Team): boolean {
  return new Date(team.publishDate) <= new Date();
}

export const TEAMS: Team[] = [
  // ── Wave 1: Launch day (20 teams) ──
  {
    slug: "danmark",
    name: "Danmarks fodboldlandshold",
    shortName: "Danmark",
    confederation: "UEFA",
    fifaCode: "DEN",
    keyword: "danmarks fodboldlandshold",
    volume: 17000,
    flagCode: "dk",
    publishDate: "2026-07-22",
  },
  {
    slug: "skotland",
    name: "Skotlands fodboldlandshold",
    shortName: "Skotland",
    confederation: "UEFA",
    fifaCode: "SCO",
    keyword: "skotlands fodboldlandshold",
    volume: 1200,
    flagCode: "gb-sct",
    publishDate: "2026-07-22",
  },
  {
    slug: "elfenbenskysten",
    name: "Elfenbenskystens fodboldlandshold",
    shortName: "Elfenbenskysten",
    confederation: "CAF",
    fifaCode: "CIV",
    keyword: "elfenbenskystens fodboldlandshold",
    volume: 1000,
    flagCode: "ci",
    publishDate: "2026-07-22",
  },
  {
    slug: "portugal",
    name: "Portugals fodboldlandshold",
    shortName: "Portugal",
    confederation: "UEFA",
    fifaCode: "POR",
    keyword: "portugals fodboldlandshold",
    volume: 800,
    flagCode: "pt",
    publishDate: "2026-07-22",
  },
  {
    slug: "frankrig",
    name: "Frankrigs fodboldlandshold",
    shortName: "Frankrig",
    confederation: "UEFA",
    fifaCode: "FRA",
    keyword: "frankrigs fodboldlandshold",
    volume: 800,
    flagCode: "fr",
    publishDate: "2026-07-22",
  },
  {
    slug: "spanien",
    name: "Spaniens fodboldlandshold",
    shortName: "Spanien",
    confederation: "UEFA",
    fifaCode: "ESP",
    keyword: "spaniens fodboldlandshold",
    volume: 800,
    flagCode: "es",
    publishDate: "2026-07-22",
  },
  {
    slug: "norge",
    name: "Norges fodboldlandshold",
    shortName: "Norge",
    confederation: "UEFA",
    fifaCode: "NOR",
    keyword: "norges fodboldlandshold",
    volume: 800,
    flagCode: "no",
    publishDate: "2026-07-22",
  },
  {
    slug: "schweiz",
    name: "Schweiz' fodboldlandshold",
    shortName: "Schweiz",
    confederation: "UEFA",
    fifaCode: "SUI",
    keyword: "schweiz' fodboldlandshold",
    volume: 800,
    flagCode: "ch",
    publishDate: "2026-07-22",
  },
  {
    slug: "kap-verde",
    name: "Kap Verdes fodboldlandshold",
    shortName: "Kap Verde",
    confederation: "CAF",
    fifaCode: "CPV",
    keyword: "kap verdes fodboldlandshold",
    volume: 800,
    flagCode: "cv",
    publishDate: "2026-07-22",
  },
  {
    slug: "sydafrika",
    name: "Sydafrikas fodboldlandshold",
    shortName: "Sydafrika",
    confederation: "CAF",
    fifaCode: "RSA",
    keyword: "sydafrikas fodboldlandshold",
    volume: 700,
    flagCode: "za",
    publishDate: "2026-07-22",
  },
  {
    slug: "tyskland",
    name: "Tysklands fodboldlandshold",
    shortName: "Tyskland",
    confederation: "UEFA",
    fifaCode: "GER",
    keyword: "tysklands fodboldlandshold",
    volume: 700,
    flagCode: "de",
    publishDate: "2026-07-22",
  },
  {
    slug: "sverige",
    name: "Sveriges fodboldlandshold",
    shortName: "Sverige",
    confederation: "UEFA",
    fifaCode: "SWE",
    keyword: "sveriges fodboldlandshold",
    volume: 600,
    flagCode: "se",
    publishDate: "2026-07-22",
  },
  {
    slug: "iran",
    name: "Irans fodboldlandshold",
    shortName: "Iran",
    confederation: "AFC",
    fifaCode: "IRN",
    keyword: "irans fodboldlandshold",
    volume: 600,
    flagCode: "ir",
    publishDate: "2026-07-22",
  },
  {
    slug: "tyrkiet",
    name: "Tyrkiets fodboldlandshold",
    shortName: "Tyrkiet",
    confederation: "UEFA",
    fifaCode: "TUR",
    keyword: "tyrkiets fodboldlandshold",
    volume: 500,
    flagCode: "tr",
    publishDate: "2026-07-22",
  },
  {
    slug: "england",
    name: "Englands fodboldlandshold",
    shortName: "England",
    confederation: "UEFA",
    fifaCode: "ENG",
    keyword: "englands fodboldlandshold",
    volume: 500,
    flagCode: "gb-eng",
    publishDate: "2026-07-22",
  },
  {
    slug: "irak",
    name: "Iraks fodboldlandshold",
    shortName: "Irak",
    confederation: "AFC",
    fifaCode: "IRQ",
    keyword: "iraks fodboldlandshold",
    volume: 450,
    flagCode: "iq",
    publishDate: "2026-07-22",
  },
  {
    slug: "brasilien",
    name: "Brasiliens fodboldlandshold",
    shortName: "Brasilien",
    confederation: "CONMEBOL",
    fifaCode: "BRA",
    keyword: "brasiliens fodboldlandshold",
    volume: 400,
    flagCode: "br",
    publishDate: "2026-07-22",
  },
  {
    slug: "italien",
    name: "Italiens fodboldlandshold",
    shortName: "Italien",
    confederation: "UEFA",
    fifaCode: "ITA",
    keyword: "italiens fodboldlandshold",
    volume: 300,
    flagCode: "it",
    publishDate: "2026-07-22",
  },
  {
    slug: "argentina",
    name: "Argentinas fodboldlandshold",
    shortName: "Argentina",
    confederation: "CONMEBOL",
    fifaCode: "ARG",
    keyword: "argentinas fodboldlandshold",
    volume: 250,
    flagCode: "ar",
    publishDate: "2026-07-22",
  },
  {
    slug: "holland",
    name: "Hollands fodboldlandshold",
    shortName: "Holland",
    confederation: "UEFA",
    fifaCode: "NED",
    keyword: "hollands fodboldlandshold",
    volume: 250,
    flagCode: "nl",
    publishDate: "2026-07-22",
  },

  // ── Wave 2: Drip-fed every 3 days (20 teams) ──
  {
    slug: "tunesien",
    name: "Tunesiens fodboldlandshold",
    shortName: "Tunesien",
    confederation: "CAF",
    fifaCode: "TUN",
    keyword: "tunesiens fodboldlandshold",
    volume: 350,
    flagCode: "tn",
    publishDate: "2026-07-25",
  },
  {
    slug: "graekenland",
    name: "Grækenlands fodboldlandshold",
    shortName: "Grækenland",
    confederation: "UEFA",
    fifaCode: "GRE",
    keyword: "grækenlands fodboldlandshold",
    volume: 350,
    flagCode: "gr",
    publishDate: "2026-07-25",
  },
  {
    slug: "ungarn",
    name: "Ungarns fodboldlandshold",
    shortName: "Ungarn",
    confederation: "UEFA",
    fifaCode: "HUN",
    keyword: "ungarns fodboldlandshold",
    volume: 300,
    flagCode: "hu",
    publishDate: "2026-07-28",
  },
  {
    slug: "japan",
    name: "Japans fodboldlandshold",
    shortName: "Japan",
    confederation: "AFC",
    fifaCode: "JPN",
    keyword: "japans fodboldlandshold",
    volume: 300,
    flagCode: "jp",
    publishDate: "2026-07-28",
  },
  {
    slug: "usa",
    name: "USA's fodboldlandshold",
    shortName: "USA",
    confederation: "CONCACAF",
    fifaCode: "USA",
    keyword: "usa's fodboldlandshold",
    volume: 300,
    flagCode: "us",
    publishDate: "2026-07-31",
  },
  {
    slug: "bosnien-hercegovina",
    name: "Bosnien-Hercegovinas fodboldlandshold",
    shortName: "Bosnien-Hercegovina",
    confederation: "UEFA",
    fifaCode: "BIH",
    keyword: "bosnien-hercegovinas fodboldlandshold",
    volume: 200,
    flagCode: "ba",
    publishDate: "2026-07-31",
  },
  {
    slug: "mexico",
    name: "Mexicos fodboldlandshold",
    shortName: "Mexico",
    confederation: "CONCACAF",
    fifaCode: "MEX",
    keyword: "mexicos fodboldlandshold",
    volume: 250,
    flagCode: "mx",
    publishDate: "2026-08-03",
  },
  {
    slug: "serbien",
    name: "Serbiens fodboldlandshold",
    shortName: "Serbien",
    confederation: "UEFA",
    fifaCode: "SRB",
    keyword: "serbiens fodboldlandshold",
    volume: 250,
    flagCode: "rs",
    publishDate: "2026-08-03",
  },
  {
    slug: "kroatien",
    name: "Kroatiens fodboldlandshold",
    shortName: "Kroatien",
    confederation: "UEFA",
    fifaCode: "CRO",
    keyword: "kroatiens fodboldlandshold",
    volume: 150,
    flagCode: "hr",
    publishDate: "2026-08-06",
  },
  {
    slug: "belgien",
    name: "Belgiens fodboldlandshold",
    shortName: "Belgien",
    confederation: "UEFA",
    fifaCode: "BEL",
    keyword: "belgiens fodboldlandshold",
    volume: 150,
    flagCode: "be",
    publishDate: "2026-08-06",
  },
  {
    slug: "polen",
    name: "Polens fodboldlandshold",
    shortName: "Polen",
    confederation: "UEFA",
    fifaCode: "POL",
    keyword: "polens fodboldlandshold",
    volume: 200,
    flagCode: "pl",
    publishDate: "2026-08-09",
  },
  {
    slug: "marokko",
    name: "Marokkos fodboldlandshold",
    shortName: "Marokko",
    confederation: "CAF",
    fifaCode: "MAR",
    keyword: "marokkos fodboldlandshold",
    volume: 200,
    flagCode: "ma",
    publishDate: "2026-08-09",
  },
  {
    slug: "australien",
    name: "Australiens fodboldlandshold",
    shortName: "Australien",
    confederation: "AFC",
    fifaCode: "AUS",
    keyword: "australiens fodboldlandshold",
    volume: 200,
    flagCode: "au",
    publishDate: "2026-08-12",
  },
  {
    slug: "canada",
    name: "Canadas fodboldlandshold",
    shortName: "Canada",
    confederation: "CONCACAF",
    fifaCode: "CAN",
    keyword: "canadas fodboldlandshold",
    volume: 200,
    flagCode: "ca",
    publishDate: "2026-08-12",
  },
  {
    slug: "uruguay",
    name: "Uruguays fodboldlandshold",
    shortName: "Uruguay",
    confederation: "CONMEBOL",
    fifaCode: "URU",
    keyword: "uruguays fodboldlandshold",
    volume: 150,
    flagCode: "uy",
    publishDate: "2026-08-15",
  },
  {
    slug: "albanien",
    name: "Albaniens fodboldlandshold",
    shortName: "Albanien",
    confederation: "UEFA",
    fifaCode: "ALB",
    keyword: "albaniens fodboldlandshold",
    volume: 150,
    flagCode: "al",
    publishDate: "2026-08-15",
  },
  {
    slug: "tjekkiet",
    name: "Tjekkiets fodboldlandshold",
    shortName: "Tjekkiet",
    confederation: "UEFA",
    fifaCode: "CZE",
    keyword: "tjekkiets fodboldlandshold",
    volume: 150,
    flagCode: "cz",
    publishDate: "2026-08-18",
  },
  {
    slug: "colombia",
    name: "Colombias fodboldlandshold",
    shortName: "Colombia",
    confederation: "CONMEBOL",
    fifaCode: "COL",
    keyword: "colombias fodboldlandshold",
    volume: 150,
    flagCode: "co",
    publishDate: "2026-08-18",
  },
  {
    slug: "new-zealand",
    name: "New Zealands fodboldlandshold",
    shortName: "New Zealand",
    confederation: "OFC",
    fifaCode: "NZL",
    keyword: "new zealands fodboldlandshold",
    volume: 250,
    flagCode: "nz",
    publishDate: "2026-08-21",
  },
  {
    slug: "chile",
    name: "Chiles fodboldlandshold",
    shortName: "Chile",
    confederation: "CONMEBOL",
    fifaCode: "CHI",
    keyword: "chiles fodboldlandshold",
    volume: 100,
    flagCode: "cl",
    publishDate: "2026-08-21",
  },
];

/** All teams (including unpublished — for generateStaticParams) */
export function getAllTeams(): Team[] {
  return TEAMS;
}

/** Only published teams (for homepage, footer, sitemap, related teams) */
export function getPublishedTeams(): Team[] {
  return TEAMS.filter(isPublished);
}

export function getTeam(slug: string): Team | undefined {
  return TEAMS.find((t) => t.slug === slug);
}

export function getTeamsByConfederation(
  confederation: Confederation
): Team[] {
  return TEAMS.filter((t) => t.confederation === confederation && isPublished(t));
}
